### ISSUE TITLE
Try docker image instead of nix bundle

### ISSUE THREAD

**Issue by srid** [srid/neuron-template#3]
See if using docker is faster to deploy.

**Comment by godu** [comment]
check out my repo https://github.com/godu/notes/blob/master/.github/workflows/pages.yml
Pulling docker is about 13s, quite similar (2s overhead) to download binary.

**Comment by srid** [comment]
I wonder if pulling the image from [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) would be a bit more faster.

**Comment by RoyiAvital** [comment]
Any chance to have a template for GitLab as well?
In GitLab one can publish a site for private repository and also limit the access to the site for private use.

By the way, which `mmark-md` extensions are enabled?

**Comment by srid** [comment]
> Any chance to have a template for GitLab as well?

Responded here: https://github.com/srid/neuron/discussions/506 (The gitlab template already uses docker image, IIRC)

> By the way, which mmark-md extensions are enabled?

Neuron has long switched from mmark-md to Pandoc ... commonmark-hs specifically. See [here](https://github.com/srid/neuron/blob/aabae6a0df7b4be2a9ed1192aac206fdfea1cec8/neuron/src/lib/Neuron/Markdown.hs#L125-L149) for list of extensions enabled. [Doc for extensions here](https://github.com/jgm/commonmark-hs/tree/master/commonmark-extensions).

**Comment by RoyiAvital** [comment]
I think the site still documents as it uses `mmark-md`.
See https://neuron.zettel.page/2014401.html.

**Comment by RoyiAvital** [comment]
@srid , I would also add a page dedicated to the MarkDown parser with the info you provided here (Which Plug In's are used).

**Comment by srid** [comment]
We have https://github.com/srid/neuron/issues/176 for that. Want to open a PR?

**Comment by RoyiAvital** [comment]
Once I get how things works (I don't get the tagging and `dirtree` from documentation) I'd be happy to assist.

**Comment by srid** [comment]
Done in https://github.com/srid/neuron-template/commit/0964f876acd7478562960fe1bae04516cb1377ed
