### ISSUE TITLE
Numbers in title magically create date field

### ISSUE THREAD

**Issue by dlqs** [srid/neuron-template#4]
I don't see this behaviour documented anywhere. Perhaps this is YAML thing? I also tried adding a `date:` field in the front matter. But it appears that something is interpreting the numbers in the title of the file and overriding it.

Raw: https://raw.githubusercontent.com/dlqs/zettel-test/master/1908201.md (no `date:` field)

Zettel: https://dlqs.github.io/zettel-test/1908201.html (screenshot below, magically has date field)
![image](https://user-images.githubusercontent.com/31354724/90649821-b4bfc200-e26d-11ea-974e-d40a2cdb82e4.png)

**Comment by srid** [comment]
@dlqs Is "1908201" an ID you created by hand (i.e., not by `neuron new`)? These are called "date IDs" which the original neuron had, and we retained them for backwards compatibility. A "date ID" is numeric with length exactly 7, and your ID matches it.

**Comment by srid** [comment]
https://github.com/srid/neuron/issues/151

**Comment by dlqs** [comment]
@srid  Yes, it was manually created. That clears it up. Thanks!
